/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import task.NewOpportunityPortal.db.tables.Advert;
import task.NewOpportunityPortal.db.tables.Category;
import task.NewOpportunityPortal.db.tables.Chat;
import task.NewOpportunityPortal.db.tables.Comment;
import task.NewOpportunityPortal.db.tables.Message;
import task.NewOpportunityPortal.db.tables.Status;
import task.NewOpportunityPortal.db.tables.Tag;
import task.NewOpportunityPortal.db.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -2127240809;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.advert</code>.
     */
    public final Advert ADVERT = task.NewOpportunityPortal.db.tables.Advert.ADVERT;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = task.NewOpportunityPortal.db.tables.Category.CATEGORY;

    /**
     * The table <code>public.chat</code>.
     */
    public final Chat CHAT = task.NewOpportunityPortal.db.tables.Chat.CHAT;

    /**
     * The table <code>public.comment</code>.
     */
    public final Comment COMMENT = task.NewOpportunityPortal.db.tables.Comment.COMMENT;

    /**
     * The table <code>public.message</code>.
     */
    public final Message MESSAGE = task.NewOpportunityPortal.db.tables.Message.MESSAGE;

    /**
     * The table <code>public.status</code>.
     */
    public final Status STATUS = task.NewOpportunityPortal.db.tables.Status.STATUS;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = task.NewOpportunityPortal.db.tables.Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = task.NewOpportunityPortal.db.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Advert.ADVERT,
            Category.CATEGORY,
            Chat.CHAT,
            Comment.COMMENT,
            Message.MESSAGE,
            Status.STATUS,
            Tag.TAG,
            User.USER);
    }
}
